-- =============================================
-- 테스트 데이터 Seed
-- 사용법:
--   1. Supabase Dashboard → SQL Editor 실행
--   2. 아래 조회 쿼리로 본인 store_id 확인
--      SELECT id FROM public.stores WHERE seller_id = auth.uid();
--   3. 또는 Dashboard → Table Editor → stores 에서 id 복사
--   4. 아래 YOUR_STORE_ID 를 실제 store id 로 교체 후 실행
-- =============================================

-- =============================================
-- 테스트 상품 삽입
-- =============================================

INSERT INTO public.products (
  store_id,
  name,
  description,
  product_type,
  category,
  retail_price,
  wholesale_price,
  min_wholesale_quantity,
  unit,
  stock,
  is_available,
  color,
  characteristics,
  image_urls,
  blooming_season,
  has_thorns,
  has_fragrance,
  min_order_quantity,
  bulk_discount_conditions,
  origin,
  deliverable_regions,
  shipping_methods,
  shipping_days_required,
  shipping_fee,
  order_cutoff_time,
  cold_packaging,
  available_shipping_days,
  expected_arrival_days,
  sale_season,
  recommended_buyer_types,
  notes
) VALUES

-- 상품 1: 레드 장미
(
  '191a92e6-4155-449c-b56f-1c25decc8aa4',
  '프리미엄 레드 장미',
  '최상급 에콰도르산 레드 장미. 줄기 길이 60cm 이상, 꽃봉오리 탐스럽고 신선도 최상.',
  'fresh_flower',
  'rose',
  15000,
  8000,
  10,
  '단',
  200,
  true,
  '["빨강"]',
  '줄기 60cm 이상, 대형 꽃봉오리',
  '[]',
  '연중',
  true,
  true,
  1,
  '[{"min_quantity": 10, "discount_rate": 5}, {"min_quantity": 30, "discount_rate": 10}]',
  '에콰도르',
  '["전국"]',
  '["새벽배송", "일반택배"]',
  '1~2일',
  3000,
  '15:00',
  true,
  '["월", "화", "수", "목", "금"]',
  '["익일", "2일 후"]',
  'year_round',
  '["wedding_event", "retail_shop", "general_consumer"]',
  '냉장 보관 시 5~7일 유지 가능'
),

-- 상품 2: 화이트 튤립
(
  'YOUR_STORE_ID',
  '화이트 튤립',
  '네덜란드산 화이트 튤립. 순백의 꽃잎이 고급스러운 분위기를 연출합니다.',
  'fresh_flower',
  'tulip',
  12000,
  6500,
  20,
  '단',
  150,
  true,
  '["흰색"]',
  '줄기 45cm, 깔끔한 흰색',
  '[]',
  '봄',
  false,
  false,
  1,
  '[{"min_quantity": 20, "discount_rate": 8}]',
  '네덜란드',
  '["전국"]',
  '["새벽배송", "일반택배"]',
  '1~2일',
  3000,
  '15:00',
  true,
  '["월", "화", "수", "목", "금"]',
  '["익일", "2일 후"]',
  'spring',
  '["wedding_event", "retail_shop"]',
  '봄 시즌 인기 상품. 물꽂이 후 2~3일 내 활짝 핍니다.'
),

-- 상품 3: 혼합 카네이션
(
  'YOUR_STORE_ID',
  '혼합 카네이션 (어버이날 특선)',
  '빨강·분홍·흰색 카네이션 혼합. 어버이날, 스승의날 선물용으로 최적.',
  'fresh_flower',
  'carnation',
  10000,
  5500,
  30,
  '단',
  300,
  true,
  '["빨강", "분홍", "흰색"]',
  '혼합 컬러, 줄기 40cm',
  '[]',
  '봄',
  false,
  true,
  1,
  '[{"min_quantity": 30, "discount_rate": 10}]',
  '국내산',
  '["전국"]',
  '["새벽배송", "일반택배", "직접배송"]',
  '당일~1일',
  2500,
  '12:00',
  true,
  '["월", "화", "수", "목", "금", "토"]',
  '["당일", "익일"]',
  'spring',
  '["general_consumer", "retail_shop"]',
  '어버이날 시즌 물량 한정. 사전 예약 권장.'
),

-- 상품 4: 해바라기
(
  'YOUR_STORE_ID',
  '대형 해바라기',
  '밝고 화사한 대형 해바라기. 꽃 지름 15cm 이상. 인테리어 및 이벤트용으로 인기.',
  'fresh_flower',
  'sunflower',
  8000,
  4000,
  20,
  '송이',
  500,
  true,
  '["노랑"]',
  '꽃 지름 15cm 이상, 대형',
  '[]',
  '여름',
  false,
  false,
  1,
  '[{"min_quantity": 20, "discount_rate": 5}]',
  '국내산',
  '["전국"]',
  '["일반택배", "직접배송"]',
  '1~2일',
  2000,
  '15:00',
  false,
  '["월", "화", "수", "목", "금"]',
  '["익일", "2일 후"]',
  'summer',
  '["general_consumer", "retail_shop", "wedding_event"]',
  '고온에 약하므로 여름철 배송 시 새벽배송 권장.'
),

-- 상품 5: 실내 관엽식물 (나무)
(
  'YOUR_STORE_ID',
  '몬스테라 중형',
  '공기 정화 효과가 뛰어난 몬스테라. 높이 50~60cm. 인테리어 식물로 인기.',
  'tree',
  'indoor_plant',
  35000,
  22000,
  5,
  '개',
  80,
  true,
  '["초록"]',
  '높이 50~60cm, 화분 포함',
  '[]',
  '연중',
  false,
  false,
  1,
  '[{"min_quantity": 5, "discount_rate": 10}]',
  '국내산',
  '["전국"]',
  '["일반택배", "직접배송"]',
  '2~3일',
  5000,
  '15:00',
  false,
  '["월", "화", "수", "목", "금"]',
  '["2일 후", "3일 후"]',
  'year_round',
  '["general_consumer", "retail_shop"]',
  '화분째 배송. 직접배송 시 안전하게 포장 제공.'
);
