-- orders 테이블: 수수료 컬럼 추가 (결제 시 필요)
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS pg_fee_rate NUMERIC NOT NULL DEFAULT 0.035,
  ADD COLUMN IF NOT EXISTS pg_fee_amount INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS commission_rate NUMERIC NOT NULL DEFAULT 0.035,
  ADD COLUMN IF NOT EXISTS commission_amount INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seller_payout INTEGER NOT NULL DEFAULT 0;

-- stores 테이블: 구독 상태 컬럼 추가
ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS is_subscription_active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS subscription_started_at TIMESTAMPTZ;
